services:
  listener:
    image: almir/webhook:2.8.1
    container_name: ${COMPOSE_PROJECT_NAME}-listener
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload -template
    volumes:
      - ./hooks.json:/etc/webhook/hooks.json:ro
      - ./scripts:/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/w7-localbase
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook.rule=Host(`webhook.w7.local`)"
      - "traefik.http.services.webhook.loadbalancer.server.port=9000"
    networks:
      - w7-ingress
    restart: unless-stopped

networks:
  w7-ingress:
    external: true